easy_admin:
    entities:
        # List the entity class name you want to manage
        ArrivalZone:
            class: App\Entity\ArrivalZone
        DepartureZone:
            class: App\Entity\DepartureZone
        Journey:
            class: App\Entity\Journey
            list:
                action: ['-new']
        Request:
            class: App\Entity\Request
            list:
                actions: ['-new']
        User:
            class: App\Entity\User
    site_name: '<em style="font-size: 80%;">Admin ElPunto</em>'
